<a href="https://colab.research.google.com/github/AribaRazi/MachineLearning/blob/main/gridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

X= df.drop('species',axis=1)
y= df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
# train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
# creating a model
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn=KNeighborsClassifier(n_neighbors=13)

model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
y_pred=model_knn.predict(X_test)
print(model_knn.score(X_test,y_test))

1.0

In [ ]:
# now using SVM

## SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm=SVC(gamma='auto')

In [ ]:
model_svm.fit(X_train,y_train)
model_svm.score(X_test,y_test)

1.0

In [ ]:
# now keep chaning the values of the parameters like C kernel etc

### now lets use the GRID SEARCH CV

In [ ]:
from sklearn.model_selection import GridSearchCV

# lets tune the hyperparameters ie creating grids
classifier = GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel' : ['liear','rbf'],
    # cv for cross validation
},cv=5,return_train_score=False)

In [ ]:
classifier.fit(X,y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
20 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'rbf', 'linear', 'sigmoid', 'poly'} or a callable. Got 'liear' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.98              nan 0.98              nan 0.96666667
        nan 0.96      ]
  warnings.warn(

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['liear', 'rbf']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00081024, 0.00233274, 0.00064874, 0.00228872, 0.00075536,
        0.00245142, 0.00072145, 0.00222111]),
 'std_fit_time': array([1.61516057e-04, 7.69354848e-05, 5.16582147e-05, 5.32489843e-05,
        2.19649818e-04, 3.26793972e-04, 1.22735791e-04, 1.77332335e-04]),
 'mean_score_time': array([0.        , 0.00179782, 0.        , 0.00172219, 0.        ,
        0.00175977, 0.        , 0.00167665]),
 'std_score_time': array([0.00000000e+00, 4.71930532e-05, 0.00000000e+00, 6.76609245e-05,
        0.00000000e+00, 1.22078042e-04, 0.00000000e+00, 5.07690741e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['liear', 'rbf', 'liear', 'rbf', 'liear', 'rbf',
                    'liear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'liear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'liear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'liear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'liear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([       nan, 0.96666667,        nan, 0.96666667,        nan,
        0.96666667,        nan, 0.96666667]),
 'split1_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1.]),
 'split2_test_score': array([       nan, 0.96666667,        nan, 0.96666667,        nan,
        0.9       ,        nan, 0.9       ]),
 'split3_test_score': array([       nan, 0.96666667,        nan, 0.96666667,        nan,
        0.96666667,        nan, 0.93333333]),
 'split4_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1.]),
 'mean_test_score': array([       nan, 0.98      ,        nan, 0.98      ,        nan,
        0.96666667,        nan, 0.96      ]),
 'std_test_score': array([       nan, 0.01632993,        nan, 0.01632993,        nan,
        0.03651484,        nan, 0.03887301]),
 'rank_test_score': array([5, 1, 5, 1, 5, 3, 5, 4], dtype=int32)}

In [ ]:
results=pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000810,0.000162,0.000000,0.000000,1,liear,"{'C': 1, 'kernel': 'liear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.002333,0.000077,0.001798,0.000047,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000649,0.000052,0.000000,0.000000,10,liear,"{'C': 10, 'kernel': 'liear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.002289,0.000053,0.001722,0.000068,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.000755,0.000220,0.000000,0.000000,20,liear,"{'C': 20, 'kernel': 'liear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.002451,0.000327,0.001760,0.000122,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,3
6,0.000721,0.000123,0.000000,0.000000,30,liear,"{'C': 30, 'kernel': 'liear'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.002221,0.000177,0.001677,0.000051,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1        liear              NaN
1        1          rbf         0.980000
2       10        liear              NaN
3       10          rbf         0.980000
4       20        liear              NaN
5       20          rbf         0.966667
6       30        liear              NaN
7       30          rbf         0.960000

In [ ]:
# now we will create same for KNN

# RANDOM SEARCH CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

classifier_r = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel' : ['liear','rbf'],
    # cv for cross validation
},n_iter=4,cv=5,return_train_score=False)

In [ ]:
classifier_r.fit(X,y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.12/dist-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'precomputed', 'rbf', 'linear', 'sigmoid', 'poly'} or a callable. Got 'liear' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.96       0.96666667        nan]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['liear', 'rbf']})

In [ ]:
results_cv=pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results_cv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008754,0.003921,0.000000,0.000000,liear,10,"{'kernel': 'liear', 'C': 10}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
1,0.011550,0.002999,0.005786,0.001421,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.9,0.933333,1.0,0.960000,0.038873,2
2,0.007528,0.003142,0.004680,0.001594,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.9,0.966667,1.0,0.966667,0.036515,1
3,0.001571,0.000943,0.000000,0.000000,liear,1,"{'kernel': 'liear', 'C': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [ ]:
results_cv[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10        liear              NaN
1       30          rbf         0.960000
2       20          rbf         0.966667
3        1        liear              NaN